<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parking Lot Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
            color: #333;
        }

        h2 {
            text-align: center;
            margin-bottom: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            padding: 8px 10px;
            border: 1px solid #999;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            color: #888;
            position: fixed;
            bottom: 20px;
            width: 100%;
        }

        .header {
            text-align: left;
            margin-bottom: 10px;
        }

        .report-meta {
            margin-bottom: 10px;
            font-size: 11px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h2>Parking Lot Report</h2>
        <div class="report-meta">
            Date: {{ \Carbon\Carbon::now()->format('d M Y, h:i A') }}<br>
            Generated by: ParkingLot System
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>QR Code</th>
                <th>Vehicle Number</th>
                <th>Location</th>
                <th>In Time</th>
                <th>Out Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $d)
                <tr>
                    <td>{{ $d['DT_RowIndex'] }}</td>
                    <td>{!! $d['qrcode'] !!}</td>
                    <td>{{ $d['vehicle_number'] }}</td>
                    <td>{{ $d['location'] }}</td>
                    <td>{{ $d['in_time'] }}</td>
                    <td>{{ $d['out_time'] }}</td>
                    <td>{{ $d['status'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} ParkingLot System. All rights reserved.
    </div>

</body>
</html>
